In [1]:
import pandas as pd
import sqlite3
import numpy as np

In [2]:
# Vancouver crime information
# Using the given sqlite3 connection:

# Store all the crimes committed after 18:00 h in a late_crimes variable.
# Store the number of crimes committed on the month with most crimes in a dangerous_month_crimes variable.

In [5]:
# # We will read the data from the sql file

# # We 1st create a connection to the sql file

# conn = sqlite3.connect(r'C:\Users\HP\Desktop\Data-Science-Foundations\Databases\van_crime_2003.sql')

# # We use the read_sql method

# db = pd.read_sql("SELECT * FROM van_crimes " , conn)

In [ ]:
# I f you look above you will notice the code will not work

# When we use sqlite.connect we are saying to connect to a database or a sqlite file. But in our case our file is a .sql. It has actual instructions like CREATE , INSERT INTO ETC. We can't query directly with SELECT * as there is no engine to interprate those words yet


# WHAT DO WE DO??

In [8]:
# We create an empty database in our RAM

conn = sqlite3.connect(':memory:')

# We now read our txt file the .sql file 

with open(r'C:\Users\HP\Desktop\Data-Science-Foundations\Databases\van_crime_2003.sql' , 'r') as file:
    sql_script = file.read()

# We execute the script to actually build the tables and insert our data

conn.executescript(sql_script)


# Now we can query with the panads read_sql

db = pd.read_sql("SELECT * FROM van_crimes" , conn)
db

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
0,Theft from Vehicle,2003,6,28.0,13.0,30.0,8XX EXPO BLVD,Central Business District,491771.63,5458295.01
1,Theft from Vehicle,2003,11,17.0,16.0,0.0,56XX OAK ST,South Cambie,490682.32,5453536.96
2,Theft from Vehicle,2003,12,30.0,14.0,0.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
3,Theft of Vehicle,2003,1,15.0,14.0,45.0,6XX W 41ST AVE,Oakridge,491372.94,5453422.83
4,Theft from Vehicle,2003,12,28.0,16.0,45.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
...,...,...,...,...,...,...,...,...,...,...
245,Break and Enter Residential/Other,2003,2,15.0,8.0,0.0,10XX HARWOOD ST,West End,490370.04,5458403.21
246,Break and Enter Residential/Other,2003,6,11.0,15.0,45.0,10XX HARWOOD ST,West End,490370.04,5458403.21
247,Theft of Vehicle,2003,4,1.0,21.0,0.0,6XX W 8TH AVE,Fairview,491445.25,5456826.01
248,Theft of Vehicle,2003,8,29.0,23.0,0.0,6XX W 8TH AVE,Fairview,491445.25,5456826.01
249,Theft of Vehicle,2003,2,6.0,9.0,10.0,6XX W CORDOVA ST,Central Business District,491865.24,5459187.85

In [10]:
# In future you may want to query and dont want to go throught all this process.

# We can create a database so that we can directly query from there

# We need to create the path to where we want to store our database file

db_path = r'C:\Users\HP\Desktop\Data-Science-Foundations\Databases\van_crime_2003.db'

# We now connect to that database authoght its empty

conn = sqlite3.connect(db_path)

# We open the sql file and execute it

with open(r'C:\Users\HP\Desktop\Data-Science-Foundations\Databases\van_crime_2003.sql' , 'r') as file:
    conn.executescript(file.read())

# We print a message saying the script has been executed and stored in the database.

print(f"SQL Script executed and stored in the database= {db_path}")

SQL Script executed and stored in the database= C:\Users\HP\Desktop\Data-Science-Foundations\Databases\van_crime_2003.db

In [ ]:
# We fo ahead and answer the questions we were asked

# Store all the crimes committed after 18:00 h in a late_crimes variable.
# Store the number of crimes committed on the month with most crimes in a dangerous_month_crimes variable.

In [45]:
# QUESTION ONE: # Store all the crimes committed after 18:00 h in a late_crimes variable.

late_crimes = db.loc[db['HOUR'] > 18.0]
late_crimes

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
12,Theft of Vehicle,2003,9,2.0,21.0,0.0,20XX E 28TH AVE,Kensington-Cedar Cottage,495267.03,5454779.05
13,Theft from Vehicle,2003,9,27.0,22.0,30.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
14,Theft from Vehicle,2003,12,17.0,21.0,0.0,31XX WILLOW ST,Fairview,491115.72,5456039.96
18,Theft from Vehicle,2003,9,1.0,20.0,10.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
19,Theft from Vehicle,2003,8,17.0,19.0,0.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
29,Theft of Vehicle,2003,1,8.0,23.0,30.0,20XX E 20TH AVE,Kensington-Cedar Cottage,495323.79,5455541.93
31,Mischief,2003,10,9.0,21.0,30.0,9XX BEATTY ST,Central Business District,491591.17,5458195.67
34,Theft from Vehicle,2003,5,21.0,19.0,0.0,56XX OAK ST,South Cambie,490682.32,5453536.96
39,Theft of Vehicle,2003,2,13.0,21.0,45.0,6XX W 41ST AVE,Oakridge,491372.94,5453422.83
41,Theft of Vehicle,2003,12,30.0,21.0,0.0,20XX E 13TH AVE,Kensington-Cedar Cottage,495346.79,5456204.45
43,Theft of Vehicle,2003,12,18.0,21.0,0.0,20XX E 13TH AVE,Kensington-Cedar Cottage,495346.79,5456204.45
44,Theft of Vehicle,2003,5,5.0,22.0,0.0,20XX E 13TH AVE,Kensington-Cedar Cottage,495346.79,5456204.45
47,Theft from Vehicle,2003,1,6.0,22.0,0.0,32XX ADANAC ST,Hastings-Sunrise,497373.96,5458296.45
67,Theft of Vehicle,2003,5,29.0,21.0,0.0,20XX COMOX ST,West End,489621.16,5459767.84
70,Theft from Vehicle,2003,5,1.0,19.0,0.0,56XX OAK ST,South Cambie,490682.32,5453536.96
75,Theft of Vehicle,2003,9,2.0,22.0,0.0,20XX COMOX ST,West End,489602.49,5459800.00
76,Theft of Vehicle,2003,3,12.0,20.0,0.0,20XX COMOX ST,West End,489602.49,5459800.00
84,Theft of Vehicle,2003,5,14.0,23.0,0.0,20XX COMMERCIAL DR,Grandview-Woodland,494933.69,5457116.79
87,Theft of Vehicle,2003,5,31.0,23.0,30.0,20XX COLUMBIA ST,Mount Pleasant,492042.40,5457188.57
89,Theft of Vehicle,2003,6,16.0,22.0,30.0,20XX CHARLES ST,Grandview-Woodland,495362.95,5457801.33
92,Theft from Vehicle,2003,10,27.0,20.0,0.0,11XX BARCLAY ST,West End,490719.76,5458990.73
96,Mischief,2003,4,29.0,19.0,30.0,5XX E 41ST AVE,Sunset,493176.45,5453348.11
97,Theft from Vehicle,2003,5,17.0,19.0,0.0,85XX SELKIRK ST,Marpole,490308.11,5450671.75
102,Theft from Vehicle,2003,10,28.0,22.0,30.0,85XX OSLER ST,Marpole,490420.20,5450728.81
105,Vehicle Collision or Pedestrian Struck (with I...,2003,12,24.0,19.0,0.0,E 12TH AVE / VICTORIA DR,Kensington-Cedar Cottage,495201.00,5456310.00
107,Mischief,2003,8,16.0,19.0,50.0,5XX E 41ST AV,Sunset,493247.08,5453341.15
109,Theft from Vehicle,2003,6,20.0,20.0,30.0,85XX LIGHTHOUSE WAY,Killarney,496436.44,5450343.65
111,Theft from Vehicle,2003,6,19.0,20.0,0.0,85XX LIGHTHOUSE WAY,Killarney,496436.21,5450361.00
120,Break and Enter Residential/Other,2003,6,14.0,22.0,0.0,10XX GRANVILLE ST,Central Business District,491000.32,5458448.65
122,Break and Enter Residential/Other,2003,9,17.0,23.0,11.0,10XX GRANVILLE ST,Central Business District,491000.32,5458448.65
125,Mischief,2003,4,29.0,20.0,30.0,10XX COTTON DR,Grandview-Woodland,494798.57,5458176.91
126,Vehicle Collision or Pedestrian Struck (with I...,2003,1,12.0,23.0,45.0,E 12TH AVE / ST CATHERINES ST,Mount Pleasant,493791.00,5456330.00
129,Break and Enter Residential/Other,2003,6,4.0,20.0,10.0,30XX KINGSWAY AVE,Renfrew-Collingwood,496941.90,5453677.36
130,Theft of Vehicle,2003,6,30.0,21.0,0.0,20XX BAYSWATER ST,Kitsilano,487559.08,5457304.49
131,Break and Enter Residential/Other,2003,6,8.0,22.0,55.0,30XX KINGSWAY AVE,Renfrew-Collingwood,496989.77,5453670.43
136,Theft from Vehicle,2003,9,8.0,20.0,30.0,5X W 11TH AVE,Mount Pleasant,492289.50,5456500.47
157,Theft from Vehicle,2003,10,24.0,20.0,0.0,5X W 13TH AVE,Mount Pleasant,492281.78,5456290.21
158,Theft from Vehicle,2003,9,5.0,22.0,30.0,5X W 13TH AVE,Mount Pleasant,492282.02,5456299.35
180,Break and Enter Residential/Other,2003,4,6.0,21.0,0.0,10XX HAMILTON ST,Central Business District,491229.78,5458167.04
183,Theft of Vehicle,2003,12,27.0,21.0,0.0,20XX ADANAC ST,Grandview-Woodland,495373.90,5458302.62
189,Theft from Vehicle,2003,12,2.0,22.0,0.0,32XX COLERIDGE AVE,Killarney,497185.65,5452601.27
190,Theft of Vehicle,2003,3,26.0,23.0,0.0,1XX WATER ST,Central Business District,492227.15,5459025.27
203,Theft of Vehicle,2003,5,17.0,19.0,45.0,1XX W PENDER ST,Central Business District,492171.05,5458703.31
206,Theft from Vehicle,2003,3,22.0,19.0,0.0,32XX COMMERCIAL DR,Kensington-Cedar Cottage,494928.19,5455946.19
208,Mischief,2003,2,23.0,19.0,0.0,5XX E 15TH AVE,Mount Pleasant,493297.52,5456053.61
211,Mischief,2003,1,23.0,20.0,0.0,9XX BUTE ST,West End,490544.46,5459030.37
212,Theft of Vehicle,2003,5,26.0,21.0,30.0,6XX W 45TH AVE,Oakridge,491405.69,5453012.38
223,Break and Enter Residential/Other,2003,12,3.0,20.0,42.0,30XX KNIGHT ST,Mount Pleasant,494440.98,5456067.19
224,Mischief,2003,1,5.0,21.0,0.0,5XX E 13TH AVE,Mount Pleasant,493235.10,5456228.79
225,Theft of Vehicle,2003,7,16.0,22.0,0.0,6XX W 57TH AVE,Marpole,491358.16,5451812.43
227,Mischief,2003,10,26.0,19.0,0.0,5XX E 11TH AVE,Mount Pleasant,493237.91,5456431.60
234,Theft from Vehicle,2003,9,29.0,23.0,26.0,84XX VICTORIA DR,Victoria-Fraserview,495186.46,5450567.37
236,Theft of Vehicle,2003,7,9.0,22.0,0.0,6XX W 6TH AVE,Fairview,491448.97,5457012.29
237,Theft of Vehicle,2003,7,14.0,23.0,59.0,6XX W 7TH AVE,Fairview,491386.59,5456921.15
238,Mischief,2003,2,28.0,22.0,0.0,5XX DUNSMUIR ST,Central Business District,491675.71,5458858.96
247,Theft of Vehicle,2003,4,1.0,21.0,0.0,6XX W 8TH AVE,Fairview,491445.25,5456826.01
248,Theft of Vehicle,2003,8,29.0,23.0,0.0,6XX W 8TH AVE,Fairview,491445.25,5456826.01

In [ ]:
# QUESTION2: # Store the number of crimes committed on the month with most crimes in a dangerous_month_crimes variable.

# Value_counts orders them from largest to smallest so you just select the item at the 1st index
dangerous_month_crimes = db['MONTH'].value_counts().head(1)


dangerous_month_crimes

MONTH
5    31
Name: count, dtype: int64

In [ ]:
# Select TYPE, MONTH, DAY and NEIGHBOURHOOD from the van_crimes table, but only the crime observations from Stanley Park or West End. Store the information in a van_crimes_df DataFrame.
# Store the count of crimes per TYPE in a crime_types_count variable.

In [ ]:
# QUESTION 3: # Select TYPE, MONTH, DAY and NEIGHBOURHOOD from the van_crimes table, but only the crime observations from Stanley Park or West End. Store the information in a van_crimes_df DataFrame.


vancrimes_filter = db.loc[:: , ('TYPE' , 'MONTH' , 'DAY' , 'NEIGHBOURHOOD')]


# A mask is a a series of true and false values

mask = vancrimes_filter['NEIGHBOURHOOD'].isin(['West End' , 'Stanley Park'])

# Apply our mask to our dataframe vancrimes_filter. This tells our df to keep only those that are true
vancrimes_df = vancrimes_filter[mask]
vancrimes_df

# OR

# columns = ['TYPE', 'MONTH', 'DAY', 'NEIGHBOURHOOD']
# van_crimes_df = db.loc[db['NEIGHBOURHOOD'].isin(['Stanley Park', 'West End']), columns]
# van_crimes_df

                                  TYPE  MONTH   DAY NEIGHBOURHOOD
2                   Theft from Vehicle     12  30.0  Stanley Park
4                   Theft from Vehicle     12  28.0  Stanley Park
5                   Theft from Vehicle     12  12.0  Stanley Park
6                   Theft from Vehicle     12  12.0  Stanley Park
9                   Theft from Vehicle     11   5.0  Stanley Park
..                                 ...    ...   ...           ...
241  Break and Enter Residential/Other      1  23.0      West End
242  Break and Enter Residential/Other      2   2.0      West End
243  Break and Enter Residential/Other      2  12.0      West End
245  Break and Enter Residential/Other      2  15.0      West End
246  Break and Enter Residential/Other      6  11.0      West End

[64 rows x 4 columns]

In [93]:
# Store the count of crimes per TYPE in a crime_types_count variable.

crime_types_count = db['TYPE'].value_counts()
crime_types_count

TYPE
Theft of Vehicle                                        100
Theft from Vehicle                                       78
Break and Enter Residential/Other                        34
Mischief                                                 29
Offence Against a Person                                  5
Vehicle Collision or Pedestrian Struck (with Injury)      4
Name: count, dtype: int64